name: CLI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  markdown-lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Super-Linter
      uses: github/super-linter@v3.3.2
      with:
        VALIDATE_ALL_CODEBASE: false
        VALIDATE_MD: true
  build-artifacts:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup MSBuild Path
        uses: warrenbuckley/Setup-MSBuild@v1
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.2
      - name: Restore NuGet Packages
        run: nuget restore .\swinc.multiplayer\swinc.multiplayer.sln
      - name: Build
        run: msbuild .\swinc.multiplayer\swinc.multiplayer.sln /p:Configuration=Release
      - name: Upload Artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          name: Release
          path: swinc.multiplayer\Core\bin\Release

